export const ADD_CLASS_START = 'ADD_CLASS_START';
export const ADD_CLASS_SUCCESS = 'ADD_CLASS_SUCCESS';
export const ADD_CLASS_FAIL = 'ADD_CLASS_FAIL';

export const EDIT_CLASS_START = 'EDIT_CLASS_START';
export const EDIT_CLASS_SUCCESS = 'EDIT_CLASS_SUCCESS';
export const EDIT_CLASS_FAIL = 'EDIT_CLASS_FAIL';

export const FETCH_CLASSES_START = 'FETCH_CLASSES_START';
export const FETCH_CLASSES_SUCCESS = 'FETCH_CLASSES_SUCCESS';
export const FETCH_CLASSES_FAIL = 'FETCH_CLASSES_FAIL';

export const ATTENDED_CLASSES_START = 'ATTENDED_CLASSES_START';
export const ATTENDED_CLASSES_SUCCESS = 'ATTENDED_CLASSES_SUCCESS';
export const ATTENDED_CLASSES_FAIL = 'ATTENDED_CLASSES_FAIL';

export const APPROVE_REJECT_START = 'APPROVE_REJECT_START';
export const APPROVE_REJECT_SUCCESS = 'APPROVE_REJECT_SUCCESS';
export const APPROVE_REJECT_FAIL = 'APPROVE_REJECT_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';
